version: 1
disable_existing_loggers: False
formatters:
  std:
    format: "%(asctime)s: %(funcName)s():%(lineno)d in %(filename)s | %(levelname)s | %(message)s"
    datefmt: "%b %d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: std
    level: INFO

  file:
    class: logging.FileHandler
    formatter: std
    level: DEBUG
    filename: bobininha.log
    mode: w
    encoding: utf-8

loggers:
  discord:
    level: WARNING
    handlers:
      - console
      - file
    propagate: False

  asyncio:
    level: WARNING
    handlers:
      - console
      - file
    propagate: False

  commands.Music:
    level: DEBUG
    handlers:
      - console
      - file
    propagate: False

  SQLite3:
    level: WARNING
    handlers:
      - console
      - file
    propagate: False

  player:
    level: WARNING
    handlers:
      - console
      - file
    propagate: False

root:
  handlers:
    - console
    - file
  level: DEBUG